import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "data", "places.json");
const out = join(here, "..", "src", "data", "places.ts");

const places = JSON.parse(readFileSync(src, "utf8"));
if (!Array.isArray(places)) throw new Error("data/places.json must be a JSON array");

const ts = `// GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source of truth: data/places.json — edit that, then run \`npm run data\`.
import type { Place } from "../types";

export const SEEDS: Place[] = ${JSON.stringify(places, null, 2)};
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, ts);
console.log(`built ${out} (${places.length} places)`);
