// GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source of truth: data/places.json — edit that, then run `npm run data`.
import type { Place } from "../types";

export const SEEDS: Place[] = [
  {
    "id": "s1",
    "cat": "area",
    "name": "Rajiv Gandhi Nagar (Talwandi)",
    "lat": 25.141,
    "lng": 75.843,
    "notes": "Key coaching neighbourhood. Allen, Resonance, hostels and mess nearby."
  },
  {
    "id": "s2",
    "cat": "area",
    "name": "Landmark City",
    "lat": 25.145,
    "lng": 75.8465,
    "notes": "Big residential + coaching locality; Landmark City intersection."
  },
  {
    "id": "s3",
    "cat": "area",
    "name": "Talwandi Market",
    "lat": 25.1385,
    "lng": 75.838,
    "notes": "Restaurants, shops and coaching branches around Talwandi circle."
  },
  {
    "id": "s4",
    "cat": "area",
    "name": "Kota Junction (railway)",
    "lat": 25.1746,
    "lng": 75.8359,
    "notes": "Main station. Rickshaw/autorickshaw hub for every coaching."
  },
  {
    "id": "s5",
    "cat": "area",
    "name": "Kishore Sagar",
    "lat": 25.1775,
    "lng": 75.835,
    "notes": "Old city lake, good for evening breaks."
  },
  {
    "id": "s6",
    "cat": "area",
    "name": "Aerodrome Circle",
    "lat": 25.126,
    "lng": 75.8495,
    "notes": "Landmark roundabout on the main city road."
  },
  {
    "id": "s7",
    "cat": "area",
    "name": "Chambal Garden",
    "lat": 25.1525,
    "lng": 75.83,
    "notes": "Riverside garden, popular jogging spot."
  },
  {
    "id": "s8",
    "cat": "area",
    "name": "Seven Wonders Park",
    "lat": 25.177,
    "lng": 75.829,
    "notes": "Park with miniature wonders of the world."
  },
  {
    "id": "s9",
    "cat": "area",
    "name": "Ramkrishnapuram",
    "lat": 25.156,
    "lng": 75.84,
    "notes": "Dense hostel + coaching belt."
  },
  {
    "id": "s10",
    "cat": "area",
    "name": "Chhawani (Chhawni Market)",
    "lat": 25.168,
    "lng": 75.84,
    "notes": "Old market area with budget shops and eateries."
  },
  {
    "id": "s11",
    "cat": "area",
    "name": "Gumanpura",
    "lat": 25.163,
    "lng": 75.844,
    "notes": "Residential area, shops and cafés."
  },
  {
    "id": "s12",
    "cat": "area",
    "name": "Mahaveer Nagar",
    "lat": 25.155,
    "lng": 75.835,
    "notes": "Quiet residential colony near Talwandi."
  },
  {
    "id": "s13",
    "cat": "area",
    "name": "Indra Vihar",
    "lat": 25.148,
    "lng": 75.85,
    "notes": "Colony with several Allen campuses."
  },
  {
    "id": "s14",
    "cat": "area",
    "name": "Dhan Mandi",
    "lat": 25.17,
    "lng": 75.838,
    "notes": "Old wholesale market, cheap eats nearby."
  },
  {
    "id": "s15",
    "cat": "area",
    "name": "Baran Road corridor",
    "lat": 25.158,
    "lng": 75.852,
    "notes": "Hostels and coaching branches along Baran road."
  },
  {
    "id": "s16",
    "cat": "area",
    "name": "University of Kota (RTC)",
    "lat": 25.164,
    "lng": 75.828,
    "notes": "University campus, also used for entrance exams."
  },
  {
    "id": "s17",
    "cat": "area",
    "name": "Brijraj Bhawan Palace",
    "lat": 25.18,
    "lng": 75.841,
    "notes": "Heritage palace, now a hotel."
  },
  {
    "id": "s18",
    "cat": "area",
    "name": "Garadia Mahadev",
    "lat": 25.07,
    "lng": 75.83,
    "notes": "Famous cliff temple on the Chambal, ~30 km from city."
  },
  {
    "id": "s22",
    "cat": "coaching",
    "name": "Resonance — Talwandi",
    "lat": 25.139,
    "lng": 75.8365,
    "notes": "Head office near Talwandi; large student base.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s23",
    "cat": "coaching",
    "name": "Resonance — Baran Road",
    "lat": 25.1605,
    "lng": 75.851,
    "notes": "Bigger campus along Baran road.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s24",
    "cat": "coaching",
    "name": "Bansal Classes",
    "lat": 25.143,
    "lng": 75.8335,
    "notes": "Old, well-known Kota institute.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s25",
    "cat": "coaching",
    "name": "Career Point — Aerodrome",
    "lat": 25.127,
    "lng": 75.848,
    "notes": "Branch near Aerodrome Circle.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s26",
    "cat": "coaching",
    "name": "Career Point — Talwandi",
    "lat": 25.1398,
    "lng": 75.841,
    "notes": "Another Career Point branch.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s27",
    "cat": "coaching",
    "name": "Aakash Institute",
    "lat": 25.1505,
    "lng": 75.839,
    "notes": "Medical + engineering prep branch.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s28",
    "cat": "coaching",
    "name": "Motion Education",
    "lat": 25.148,
    "lng": 75.8325,
    "notes": "IIT-JEE / NEET coaching, Talwandi side.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s29",
    "cat": "coaching",
    "name": "Vidyamandir Classes",
    "lat": 25.1465,
    "lng": 75.844,
    "notes": "JEE coaching branch.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s30",
    "cat": "coaching",
    "name": "Narayana IIT / NEET",
    "lat": 25.157,
    "lng": 75.842,
    "notes": "Chain coaching near R.K. Puram.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s31",
    "cat": "coaching",
    "name": "Etoos India",
    "lat": 25.159,
    "lng": 75.853,
    "notes": "Online + offline program, Baran road side.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s32",
    "cat": "coaching",
    "name": "IITian's PACE (Kota)",
    "lat": 25.152,
    "lng": 75.847,
    "notes": "Kota centre of the PACE chain.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s33",
    "cat": "coaching",
    "name": "Prabhav Classes",
    "lat": 25.1535,
    "lng": 75.8415,
    "notes": "Local coaching, R.K. Puram.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s91",
    "cat": "coaching",
    "name": "Allen SANKALP",
    "lat": 25.1492,
    "lng": 75.8495,
    "notes": "Head office — CP-6, Allen Sankalp Road, Rajiv Gandhi Nagar, Indra Vihar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s92",
    "cat": "coaching",
    "name": "Allen SAMARTH",
    "lat": 25.1502,
    "lng": 75.8508,
    "notes": "5/13, Instrumentation Limited Colony, Indra Vihar, Mahaveer Nagar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s93",
    "cat": "coaching",
    "name": "Allen SABAL",
    "lat": 25.1498,
    "lng": 75.849,
    "notes": "CP-07, Indra Vihar — also hosts ALLEN Global.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s94",
    "cat": "coaching",
    "name": "Allen SABAL-2",
    "lat": 25.15,
    "lng": 75.8485,
    "notes": "Indra Vihar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s95",
    "cat": "coaching",
    "name": "Allen SAFALYA",
    "lat": 25.1462,
    "lng": 75.8478,
    "notes": "Allen Safalya Road, Rajiv Gandhi Nagar, Instrumentation Limited Colony.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s96",
    "cat": "coaching",
    "name": "Allen SAFALYA-2",
    "lat": 25.1468,
    "lng": 75.8472,
    "notes": "Plot 1, Rajiv Gandhi Nagar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s97",
    "cat": "coaching",
    "name": "Allen SAAKAR",
    "lat": 25.1472,
    "lng": 75.846,
    "notes": "Plot No. 6, Jhalawar Road, opposite City Mall, Rajiv Gandhi Nagar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s98",
    "cat": "coaching",
    "name": "Allen SAMANVAYA (PNCF)",
    "lat": 25.139,
    "lng": 75.8395,
    "notes": "No. C210/2, Sector-C, Talwandi.",
    "hours": "9:00 AM – 7:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s99",
    "cat": "coaching",
    "name": "Allen SAMYAK",
    "lat": 25.1455,
    "lng": 75.8468,
    "notes": "Samyak Campus & Samyak 2 — Landmark City, Main Road, Kunhari.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s100",
    "cat": "coaching",
    "name": "Allen SANGYAN (PNCF)",
    "lat": 25.1448,
    "lng": 75.8474,
    "notes": "Block FGH, Plot No. 4, Kunhari, Electricity Board Area.",
    "hours": "9:00 AM – 7:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s101",
    "cat": "coaching",
    "name": "Allen SRAJIT-4",
    "lat": 25.1595,
    "lng": 75.8528,
    "notes": "Srajit 2, 3 & 4 — Road No. 2, IPIA.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s102",
    "cat": "coaching",
    "name": "Allen SATYARTH",
    "lat": 25.1508,
    "lng": 75.8555,
    "notes": "Satyarth 1 — New Jawahar Nagar, Talwandi.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s103",
    "cat": "coaching",
    "name": "Allen SUPATH",
    "lat": 25.1602,
    "lng": 75.8518,
    "notes": "Baran Road, Naya Nohra, Borkhandi.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s104",
    "cat": "coaching",
    "name": "Allen SUMATI (PNCF)",
    "lat": 25.1425,
    "lng": 75.854,
    "notes": "CP-22, Vivekananda Nagar.",
    "hours": "9:00 AM – 7:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s34",
    "cat": "testcentre",
    "name": "Prometric CBT Centre",
    "lat": 25.1405,
    "lng": 75.84,
    "notes": "Computer-based test centre near Talwandi (approx).",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s35",
    "cat": "testcentre",
    "name": "Prometric CBT — R.K. Puram",
    "lat": 25.1565,
    "lng": 75.8385,
    "notes": "Second Prometric centre (approx).",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s36",
    "cat": "testcentre",
    "name": "Pearson VUE Test Centre",
    "lat": 25.1545,
    "lng": 75.845,
    "notes": "Certification exams (approx).",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s37",
    "cat": "testcentre",
    "name": "NTA CBT Centre (Govt College)",
    "lat": 25.1655,
    "lng": 75.839,
    "notes": "JEE Main / NEET-style centre (approx).",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 0
  },
  {
    "id": "s38",
    "cat": "testcentre",
    "name": "University CBT Centre",
    "lat": 25.165,
    "lng": 75.8295,
    "notes": "Exam centre at University of Kota.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 0
  },
  {
    "id": "s105",
    "cat": "testcentre",
    "name": "Viable Solutions (CBT)",
    "lat": 25.1355,
    "lng": 75.834,
    "notes": "35, Vishwakarma Circle, Subhash Nagar, Rangbari. Google 3.9★ (976 reviews).",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1,
    "rating": 3.9,
    "ratingCount": 976
  },
  {
    "id": "s106",
    "cat": "testcentre",
    "name": "Digital DKD (Desh Ki Dharti Complex)",
    "lat": 25.134,
    "lng": 75.835,
    "notes": "Ground Floor, Desh ki Dharti Complex, Sewaram Kishandas Road, Rangbari.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s107",
    "cat": "testcentre",
    "name": "Dream 27 CBT Test Centre",
    "lat": 25.141,
    "lng": 75.8405,
    "notes": "Premium computer-based test centre, Talwandi side (approx).",
    "hours": "9:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s108",
    "cat": "testcentre",
    "name": "Allen Test Center (Rangbari)",
    "lat": 25.135,
    "lng": 75.8355,
    "notes": "Plot No. 2, Vishwakarma Nagar, Transport Nagar, Rangbari.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s39",
    "cat": "restaurant",
    "name": "Juhhi Kachori Bhandar",
    "lat": 25.173,
    "lng": 75.834,
    "notes": "Famous Kota kachori spot, old city.",
    "hours": "7:00 AM – 12:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s40",
    "cat": "restaurant",
    "name": "Mohan Maheshwari Kachori",
    "lat": 25.169,
    "lng": 75.837,
    "notes": "Long-running kachori-sweets shop.",
    "hours": "7:00 AM – 9:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s41",
    "cat": "restaurant",
    "name": "Rana's Kachori & Sweets",
    "lat": 25.14,
    "lng": 75.835,
    "notes": "Local breakfast favourite near Talwandi.",
    "hours": "7:00 AM – 9:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s42",
    "cat": "restaurant",
    "name": "Sagar Ratna",
    "lat": 25.147,
    "lng": 75.8385,
    "notes": "South Indian vegetarian chain.",
    "hours": "9:00 AM – 11:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s43",
    "cat": "restaurant",
    "name": "Pizza Hut",
    "lat": 25.149,
    "lng": 75.8415,
    "notes": "Chain outlet in the market area.",
    "hours": "11:00 AM – 11:00 PM",
    "open": true,
    "price": 3
  },
  {
    "id": "s44",
    "cat": "restaurant",
    "name": "Domino's Pizza",
    "lat": 25.1445,
    "lng": 75.8345,
    "notes": "Quick delivery for hostel students.",
    "hours": "11:00 AM – 11:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s45",
    "cat": "restaurant",
    "name": "McDonald's",
    "lat": 25.129,
    "lng": 75.847,
    "notes": "Near Aerodrome Circle.",
    "hours": "10:00 AM – 11:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s46",
    "cat": "restaurant",
    "name": "KFC",
    "lat": 25.15,
    "lng": 75.845,
    "notes": "Chain outlet near Landmark.",
    "hours": "11:00 AM – 11:00 PM",
    "open": true,
    "price": 3
  },
  {
    "id": "s47",
    "cat": "restaurant",
    "name": "Bikanervala",
    "lat": 25.148,
    "lng": 75.836,
    "notes": "Sweets + snacks chain.",
    "hours": "8:00 AM – 10:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s48",
    "cat": "restaurant",
    "name": "Hotel Krishna (veg thali)",
    "lat": 25.171,
    "lng": 75.836,
    "notes": "Budget thali place, old city.",
    "hours": "11:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s49",
    "cat": "restaurant",
    "name": "Sharma Dhaba",
    "lat": 25.1555,
    "lng": 75.85,
    "notes": "Roadside dhaba, Baran road side.",
    "hours": "12:00 PM – 11:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s50",
    "cat": "restaurant",
    "name": "Coffee Culture",
    "lat": 25.146,
    "lng": 75.84,
    "notes": "Café for group study breaks.",
    "hours": "10:00 AM – 11:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s51",
    "cat": "restaurant",
    "name": "Chai Point — Gumanpura",
    "lat": 25.1625,
    "lng": 75.8435,
    "notes": "Tea + snacks spot.",
    "hours": "8:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s52",
    "cat": "restaurant",
    "name": "Amul Parlour — Talwandi",
    "lat": 25.139,
    "lng": 75.839,
    "notes": "Ice cream and quick bites.",
    "hours": "10:00 AM – 11:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s53",
    "cat": "salon",
    "name": "Green Trends Unisex Salon",
    "lat": 25.146,
    "lng": 75.8425,
    "notes": "Chain salon in the coaching belt.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s54",
    "cat": "salon",
    "name": "Lakme Salon",
    "lat": 25.1495,
    "lng": 75.8375,
    "notes": "Known salon, book ahead on weekends.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 3
  },
  {
    "id": "s55",
    "cat": "salon",
    "name": "Jawed Habib",
    "lat": 25.147,
    "lng": 75.8455,
    "notes": "Budget-friendly chain salon.",
    "hours": "10:00 AM – 9:30 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s56",
    "cat": "salon",
    "name": "Looks & Luxe Salon",
    "lat": 25.142,
    "lng": 75.838,
    "notes": "Salon near Talwandi circle.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s57",
    "cat": "salon",
    "name": "Royal Salon",
    "lat": 25.151,
    "lng": 75.8405,
    "notes": "Salon near R.K. Puram.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s58",
    "cat": "salon",
    "name": "Cuts & Curls — Landmark",
    "lat": 25.145,
    "lng": 75.847,
    "notes": "Salon in Landmark City.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s59",
    "cat": "shop",
    "name": "Gaurav Book Store",
    "lat": 25.1408,
    "lng": 75.8388,
    "notes": "Exam guides, PYQ booklets, stationery.",
    "hours": "9:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s60",
    "cat": "shop",
    "name": "Rajkamal Stationers",
    "lat": 25.156,
    "lng": 75.841,
    "notes": "Stationery + test copies, R.K. Puram.",
    "hours": "9:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s61",
    "cat": "shop",
    "name": "Photocopy & Spiral Mart",
    "lat": 25.1438,
    "lng": 75.8395,
    "notes": "Cheap printing, spiral binding, test copies.",
    "hours": "9:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s62",
    "cat": "shop",
    "name": "Electronics & Mobile Shop",
    "lat": 25.1478,
    "lng": 75.84,
    "notes": "Chargers, calculators, accessories.",
    "hours": "10:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s63",
    "cat": "shop",
    "name": "Supermarket (groceries)",
    "lat": 25.1455,
    "lng": 75.8365,
    "notes": "Hostel essentials and snacks.",
    "hours": "9:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s64",
    "cat": "shop",
    "name": "Reliance Digital",
    "lat": 25.13,
    "lng": 75.848,
    "notes": "Electronics chain near Aerodrome.",
    "hours": "10:00 AM – 10:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s65",
    "cat": "shop",
    "name": "Kota Sports Shop",
    "lat": 25.166,
    "lng": 75.841,
    "notes": "Sports equipment and uniform shops.",
    "hours": "10:00 AM – 9:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s66",
    "cat": "shop",
    "name": "Cycle & Scooter Repair",
    "lat": 25.154,
    "lng": 75.838,
    "notes": "Hostel-area bike repair point.",
    "hours": "9:00 AM – 8:00 PM",
    "open": true,
    "price": 0
  },
  {
    "id": "s67",
    "cat": "medical",
    "name": "MBS Hospital",
    "lat": 25.152,
    "lng": 75.842,
    "notes": "Multi-speciality private hospital (approx).",
    "hours": "24x7",
    "open": true,
    "price": 3
  },
  {
    "id": "s68",
    "cat": "medical",
    "name": "24x7 Pharmacy — Talwandi",
    "lat": 25.1395,
    "lng": 75.8385,
    "notes": "Late-night chemist near Talwandi.",
    "hours": "24x7",
    "open": true,
    "price": 1
  },
  {
    "id": "s69",
    "cat": "medical",
    "name": "Government Hospital",
    "lat": 25.162,
    "lng": 75.837,
    "notes": "City government hospital (approx).",
    "hours": "24x7",
    "open": true,
    "price": 1
  },
  {
    "id": "s70",
    "cat": "medical",
    "name": "MedPlus Pharmacy",
    "lat": 25.1475,
    "lng": 75.844,
    "notes": "Discount pharmacy chain.",
    "hours": "9:00 AM – 10:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s71",
    "cat": "medical",
    "name": "Dental & Physio Clinic",
    "lat": 25.157,
    "lng": 75.8395,
    "notes": "R.K. Puram clinic.",
    "hours": "10:00 AM – 8:00 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s72",
    "cat": "stay",
    "name": "Allen Hostel Complex",
    "lat": 25.155,
    "lng": 75.841,
    "notes": "R.K. Puram hostel cluster (approx)."
  },
  {
    "id": "s73",
    "cat": "stay",
    "name": "PG Mess & Rooms — Talwandi",
    "lat": 25.14,
    "lng": 75.842,
    "notes": "Budget PG + mess (approx)."
  },
  {
    "id": "s74",
    "cat": "stay",
    "name": "Boys Hostel — Baran Road",
    "lat": 25.159,
    "lng": 75.8515,
    "notes": "Hostel strip along Baran road (approx)."
  },
  {
    "id": "s75",
    "cat": "stay",
    "name": "Girls Hostel — R.K. Puram",
    "lat": 25.1565,
    "lng": 75.8435,
    "notes": "Approx location, check before booking."
  },
  {
    "id": "s76",
    "cat": "stay",
    "name": "Mess & Tiffin — Landmark",
    "lat": 25.1452,
    "lng": 75.846,
    "notes": "Daily tiffin/mess option (approx)."
  },
  {
    "id": "s77",
    "cat": "stay",
    "name": "Ayushmann Inn Hostel",
    "lat": 25.147,
    "lng": 75.847,
    "notes": "Mangal Bhawan Complex, Mala Road, Rajiv Gandhi Nagar. Approx — drag to the exact spot."
  },
  {
    "id": "s78",
    "cat": "stay",
    "name": "Samay Girls Hostel",
    "lat": 25.1505,
    "lng": 75.841,
    "notes": "Near Allen, 10-L-4 Parijat Yojna, Mahaveer Nagar III."
  },
  {
    "id": "s79",
    "cat": "stay",
    "name": "SSD Residency Boys Hostel",
    "lat": 25.159,
    "lng": 75.8535,
    "notes": "H-36-B, Electronics Complex, IPIA, Road No. 1."
  },
  {
    "id": "s80",
    "cat": "stay",
    "name": "Purvanchal Hostel",
    "lat": 25.138,
    "lng": 75.8385,
    "notes": "437-A, Modern School Road, Talwandi."
  },
  {
    "id": "s81",
    "cat": "stay",
    "name": "Govindam Boys Hostel",
    "lat": 25.16,
    "lng": 75.854,
    "notes": "H-3(C), Electronic Complex, Road No. 1, IPIA."
  },
  {
    "id": "s82",
    "cat": "stay",
    "name": "K.K Residency",
    "lat": 25.148,
    "lng": 75.8505,
    "notes": "B-177, opp. Global Public School, Indra Vihar."
  },
  {
    "id": "s83",
    "cat": "stay",
    "name": "Hari Om Bhawan Boys Hostel",
    "lat": 25.1475,
    "lng": 75.8465,
    "notes": "525, Rajiv Gandhi Nagar Phase II."
  },
  {
    "id": "s84",
    "cat": "stay",
    "name": "Shah Jain Residency",
    "lat": 25.1585,
    "lng": 75.853,
    "notes": "H-1-10, Electronic Complex, IPIA."
  },
  {
    "id": "s85",
    "cat": "stay",
    "name": "Raghukul Residency",
    "lat": 25.1495,
    "lng": 75.829,
    "notes": "Plot 10, Vigyan Nagar, Vistar Yojna Chouraha."
  },
  {
    "id": "s86",
    "cat": "stay",
    "name": "Gagan Residency Girls Hostel",
    "lat": 25.1455,
    "lng": 75.8472,
    "notes": "A-80, 81, Landmark City, Kunadi."
  },
  {
    "id": "s87",
    "cat": "stay",
    "name": "Oasis Residency Boys Hostel",
    "lat": 25.1445,
    "lng": 75.8468,
    "notes": "Landmark City, Kunadi."
  },
  {
    "id": "s88",
    "cat": "stay",
    "name": "Allen Luxurious Hostel",
    "lat": 25.1452,
    "lng": 75.846,
    "notes": "Ramanuj Mansion, Block FGH, Landmark City, Kunhari."
  },
  {
    "id": "s89",
    "cat": "stay",
    "name": "Big Brother Hostel",
    "lat": 25.171,
    "lng": 75.837,
    "notes": "Near Kota Junction, old city side."
  },
  {
    "id": "s90",
    "cat": "stay",
    "name": "Prakash Deep Hostel",
    "lat": 25.175,
    "lng": 75.836,
    "notes": "Old city, near Kishore Sagar."
  },
  {
    "id": "s109",
    "cat": "testcentre",
    "name": "Parikalak Test Center",
    "lat": 25.1415,
    "lng": 75.841,
    "notes": "B-285, Commerce College Road, Sector-B, Talwandi.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s110",
    "cat": "testcentre",
    "name": "Rajrani Tower (RGCSM)",
    "lat": 25.1575,
    "lng": 75.8525,
    "notes": "H-1-6, IT Park, Road No. 4, Jhalawar Road, IPIA.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s111",
    "cat": "testcentre",
    "name": "Interstellar Infotech",
    "lat": 25.136,
    "lng": 75.832,
    "notes": "Plot No. 2, near SkyPark Building, Subhash Nagar First, Transport Nagar, Rangbari.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s112",
    "cat": "testcentre",
    "name": "Bits N Bytes Infocom",
    "lat": 25.153,
    "lng": 75.835,
    "notes": "Plot No. 27, New Stone Mandi, near Gobariya Bawari Circle, Mahaveer Nagar.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s113",
    "cat": "testcentre",
    "name": "Ginger Labs / Modi Educational Complex",
    "lat": 25.128,
    "lng": 75.85,
    "notes": "Gate No. 1, 1st Floor, Modi Educational Complex, Dadabari.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s114",
    "cat": "testcentre",
    "name": "Modi Institute of Technology and Management (MIMT)",
    "lat": 25.1282,
    "lng": 75.8503,
    "notes": "Gate No. 2, Modi Educational Complex, Dadabari.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s115",
    "cat": "testcentre",
    "name": "Digital Desk",
    "lat": 25.1545,
    "lng": 75.8345,
    "notes": "H-110, Industrial Area No. 4, near HP Adhunik Gas Agency, Mahaveer Nagar.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s116",
    "cat": "testcentre",
    "name": "Phoenix Online Examination Centre",
    "lat": 25.105,
    "lng": 75.858,
    "notes": "Near Daswani Dental College, RIICO Ranpur (approx).",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s117",
    "cat": "testcentre",
    "name": "A4 Solutions",
    "lat": 25.129,
    "lng": 75.851,
    "notes": "Below Central Bank of India, Shastri Nagar, Dadabari.",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s118",
    "cat": "testcentre",
    "name": "Shiv Jyoti International School",
    "lat": 25.106,
    "lng": 75.859,
    "notes": "IPD-05, Jhalawar Road, RIICO Institutional Area, Ranpur (approx).",
    "hours": "9:00 AM – 6:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s119",
    "cat": "testcentre",
    "name": "Allen Career Institute, Sambandh Lab",
    "lat": 25.1515,
    "lng": 75.8395,
    "notes": "10-D-16, Parijat Colony, Mahaveer Nagar Housing Board Colony.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s120",
    "cat": "testcentre",
    "name": "ALLEN Digital Head Office",
    "lat": 25.159,
    "lng": 75.852,
    "notes": "One Biz Square, A-12(a), Road No. 1, IPIA.",
    "hours": "8:00 AM – 8:00 PM",
    "open": true,
    "price": 1
  },
  {
    "id": "s121",
    "cat": "coaching",
    "name": "Allen SUKALP",
    "lat": 25.149,
    "lng": 75.8505,
    "notes": "A-781, Indra Vihar, Mahaveer Nagar.",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  },
  {
    "id": "s122",
    "cat": "coaching",
    "name": "Allen SAROKAR",
    "lat": 25.118,
    "lng": 75.845,
    "notes": "No. C10, Nursery Road, Kota Airport Area, Talwandi (approx).",
    "hours": "8:00 AM – 8:30 PM",
    "open": true,
    "price": 2
  }
];
